# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 640)
        Dialog.setMinimumSize(QtCore.QSize(70, 60))
        Dialog.setStyleSheet("background-color: rgb(194, 194, 194);")
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setMinimumSize(QtCore.QSize(350, 100))
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(400, 50))
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_CE = QtWidgets.QPushButton(Dialog)
        self.btn_CE.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_CE.setObjectName("btn_CE")
        self.gridLayout.addWidget(self.btn_CE, 0, 1, 1, 1)
        self.btn_divide = QtWidgets.QPushButton(Dialog)
        self.btn_divide.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_divide.setObjectName("btn_divide")
        self.gridLayout.addWidget(self.btn_divide, 1, 3, 1, 1)
        self.btn_sign = QtWidgets.QPushButton(Dialog)
        self.btn_sign.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_sign.setObjectName("btn_sign")
        self.gridLayout.addWidget(self.btn_sign, 5, 0, 1, 1)
        self.btn_multiple = QtWidgets.QPushButton(Dialog)
        self.btn_multiple.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_multiple.setObjectName("btn_multiple")
        self.gridLayout.addWidget(self.btn_multiple, 2, 3, 1, 1)
        self.btn_percent = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_percent.sizePolicy().hasHeightForWidth())
        self.btn_percent.setSizePolicy(sizePolicy)
        self.btn_percent.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_percent.setObjectName("btn_percent")
        self.gridLayout.addWidget(self.btn_percent, 0, 0, 1, 1)
        self.btn_minus = QtWidgets.QPushButton(Dialog)
        self.btn_minus.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_minus.setStyleSheet("border-image: url(:/newPrefix/minus.png);")
        self.btn_minus.setText("")
        self.btn_minus.setObjectName("btn_minus")
        self.gridLayout.addWidget(self.btn_minus, 3, 3, 1, 1)
        self.btn_del = QtWidgets.QPushButton(Dialog)
        self.btn_del.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_del.setObjectName("btn_del")
        self.gridLayout.addWidget(self.btn_del, 0, 3, 1, 1)
        self.btn_x_2 = QtWidgets.QPushButton(Dialog)
        self.btn_x_2.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_x_2.setObjectName("btn_x_2")
        self.gridLayout.addWidget(self.btn_x_2, 1, 1, 1, 1)
        self.btn_1_x = QtWidgets.QPushButton(Dialog)
        self.btn_1_x.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_1_x.setObjectName("btn_1_x")
        self.gridLayout.addWidget(self.btn_1_x, 1, 0, 1, 1)
        self.btn_root = QtWidgets.QPushButton(Dialog)
        self.btn_root.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_root.setStyleSheet("border-image: url(:/newPrefix/root.png);")
        self.btn_root.setText("")
        self.btn_root.setObjectName("btn_root")
        self.gridLayout.addWidget(self.btn_root, 1, 2, 1, 1)
        self.btn_C = QtWidgets.QPushButton(Dialog)
        self.btn_C.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_C.setObjectName("btn_C")
        self.gridLayout.addWidget(self.btn_C, 0, 2, 1, 1)
        self.btn_plus = QtWidgets.QPushButton(Dialog)
        self.btn_plus.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_plus.setStyleSheet("border-image: url(:/newPrefix/plus.png);")
        self.btn_plus.setText("")
        self.btn_plus.setObjectName("btn_plus")
        self.gridLayout.addWidget(self.btn_plus, 4, 3, 1, 1)
        self.btn_result = QtWidgets.QPushButton(Dialog)
        self.btn_result.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_result.setStyleSheet("border-image: url(:/newPrefix/result.png);")
        self.btn_result.setText("")
        self.btn_result.setObjectName("btn_result")
        self.gridLayout.addWidget(self.btn_result, 5, 3, 1, 1)
        self.btn_0 = QtWidgets.QPushButton(Dialog)
        self.btn_0.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_0.setStyleSheet("border-image: url(:/newPrefix/0.png);")
        self.btn_0.setText("")
        self.btn_0.setObjectName("btn_0")
        self.gridLayout.addWidget(self.btn_0, 5, 1, 1, 1)
        self.btn_dot = QtWidgets.QPushButton(Dialog)
        self.btn_dot.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_dot.setObjectName("btn_dot")
        self.gridLayout.addWidget(self.btn_dot, 5, 2, 1, 1)
        self.btn_3 = QtWidgets.QPushButton(Dialog)
        self.btn_3.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_3.setStyleSheet("border-image: url(:/newPrefix/3.png);")
        self.btn_3.setText("")
        self.btn_3.setObjectName("btn_3")
        self.gridLayout.addWidget(self.btn_3, 4, 2, 1, 1)
        self.btn_2 = QtWidgets.QPushButton(Dialog)
        self.btn_2.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_2.setStyleSheet("border-image: url(:/newPrefix/2.png);")
        self.btn_2.setText("")
        self.btn_2.setObjectName("btn_2")
        self.gridLayout.addWidget(self.btn_2, 4, 1, 1, 1)
        self.btn_1 = QtWidgets.QPushButton(Dialog)
        self.btn_1.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_1.setStyleSheet("border-image: url(:/newPrefix/1.png);")
        self.btn_1.setText("")
        self.btn_1.setObjectName("btn_1")
        self.gridLayout.addWidget(self.btn_1, 4, 0, 1, 1)
        self.btn_4 = QtWidgets.QPushButton(Dialog)
        self.btn_4.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_4.setStyleSheet("border-image: url(:/newPrefix/4.png);")
        self.btn_4.setText("")
        self.btn_4.setObjectName("btn_4")
        self.gridLayout.addWidget(self.btn_4, 3, 0, 1, 1)
        self.btn_5 = QtWidgets.QPushButton(Dialog)
        self.btn_5.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_5.setStyleSheet("border-image: url(:/newPrefix/5.png);")
        self.btn_5.setText("")
        self.btn_5.setObjectName("btn_5")
        self.gridLayout.addWidget(self.btn_5, 3, 1, 1, 1)
        self.btn_6 = QtWidgets.QPushButton(Dialog)
        self.btn_6.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_6.setStyleSheet("border-image: url(:/newPrefix/6.png);")
        self.btn_6.setText("")
        self.btn_6.setObjectName("btn_6")
        self.gridLayout.addWidget(self.btn_6, 3, 2, 1, 1)
        self.btn_9 = QtWidgets.QPushButton(Dialog)
        self.btn_9.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_9.setStyleSheet("\n"
"border-image: url(:/newPrefix/9.png);")
        self.btn_9.setText("")
        self.btn_9.setObjectName("btn_9")
        self.gridLayout.addWidget(self.btn_9, 2, 2, 1, 1)
        self.btn_8 = QtWidgets.QPushButton(Dialog)
        self.btn_8.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_8.setStyleSheet("border-image: url(:/newPrefix/8.png);")
        self.btn_8.setText("")
        self.btn_8.setObjectName("btn_8")
        self.gridLayout.addWidget(self.btn_8, 2, 1, 1, 1)
        self.btn_7 = QtWidgets.QPushButton(Dialog)
        self.btn_7.setMinimumSize(QtCore.QSize(70, 60))
        self.btn_7.setStyleSheet("border-image: url(:/newPrefix/7.png);")
        self.btn_7.setText("")
        self.btn_7.setObjectName("btn_7")
        self.gridLayout.addWidget(self.btn_7, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_CE.setText(_translate("Dialog", "CE"))
        self.btn_divide.setText(_translate("Dialog", "/"))
        self.btn_sign.setText(_translate("Dialog", "+/-"))
        self.btn_multiple.setText(_translate("Dialog", "X"))
        self.btn_percent.setText(_translate("Dialog", "%"))
        self.btn_del.setText(_translate("Dialog", "del"))
        self.btn_x_2.setText(_translate("Dialog", "x^2"))
        self.btn_1_x.setText(_translate("Dialog", "1/x"))
        self.btn_C.setText(_translate("Dialog", "C"))
        self.btn_dot.setText(_translate("Dialog", "."))

import res

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

